
image:
  - base: sdxl_1_0
    pipelines:
      txt2img: StableDiffusionXLTextToImagePipeline
      img2img: StableDiffusionXLImageToImagePipeline
      inpaint: StableDiffusionXLInpaintPipeline
      txt2img_controlnet: StableDiffusionXLTextToImageControlNetPipeline
    models:
      - id: stabilityai/stable-diffusion-xl-base-1.0
      - id: stabilityai/stable-diffusion-xl-refiner-1.0
  - base: kandinsky_2_1
    pipelines:
      txt2img: KandinskyTextToImagePipeline
      img2img: KandinskyImageToImagePipeline
      interpolate: KandinskyInterpolatePipeline
    models:
      - id: kandinsky-community/kandinsky-2-1
        id2: kandinsky-community/kandinsky-2-1-prior
  - base: df_1_0
    pipelines:
      txt2img: DeepFloydTextToImagePipeline
    models:
      - id: DeepFloyd/IF-I-M-v1.0
        id2: DeepFloyd/IF-II-M-v1.0
        id3: stabilityai/stable-diffusion-x4-upscaler
      - id: DeepFloyd/IF-I-L-v1.0
        id2: DeepFloyd/IF-II-L-v1.0
        id3: stabilityai/stable-diffusion-x4-upscaler
      - id: DeepFloyd/IF-I-XL-v1.0
        id2: DeepFloyd/IF-II-L-v1.0
        id3: stabilityai/stable-diffusion-x4-upscaler
  - base: sd_2_1
    pipelines:
      txt2img: StableDiffusionTextToImagePipeline
      img2img: StableDiffusionImageToImagePipeline
      txt2img_controlnet: StableDiffusionTextToImageControlNetPipeline
      img2img_controlnet: StableDiffusionImageToImageControlNetPipeline
    models:
      - id: stabilityai/stable-diffusion-2-1  # official
      - id: stabilityai/stable-diffusion-2-1-base  # official
      - id: stablediffusionapi/illuminati-diffusion
  - base: sd_1_5
    pipelines:
      txt2img: StableDiffusionTextToImagePipeline
      img2img: StableDiffusionImageToImagePipeline
      inpaint: StableDiffusionInpaintPipeline
      txt2img_controlnet: StableDiffusionTextToImageControlNetPipeline
      img2img_controlnet: StableDiffusionImageToImageControlNetPipeline
      inpaint_controlnet: StableDiffusionInpaintControlNetPipeline
    models:
      - id: runwayml/stable-diffusion-v1-5  # official
        vae: stabilityai/sd-vae-ft-mse
      - id: Aybeeceedee/knollingcase
        vae: stabilityai/sd-vae-ft-mse
        phrase: knollingcase
      - id: danbrown/Lyriel-v1-5
        vae: stabilityai/sd-vae-ft-mse
      - id: darkstorm2150/Protogen_v2.2_Official_Release
        vae: stabilityai/sd-vae-ft-mse
      - id: darkstorm2150/Protogen_x3.4_Official_Release
        vae: stabilityai/sd-vae-ft-mse
      - id: darkstorm2150/Protogen_x5.3_Official_Release
        vae: stabilityai/sd-vae-ft-mse
      - id: darkstorm2150/Protogen_x5.8_Official_Release
        vae: stabilityai/sd-vae-ft-mse
      - id: digiplay/Juggernaut_final
        vae: stabilityai/sd-vae-ft-mse
      - id: dreamlike-art/dreamlike-diffusion-1.0
        vae: stabilityai/sd-vae-ft-mse
        phrase: dreamlikeart
      - id: dreamlike-art/dreamlike-photoreal-2.0
        vae: stabilityai/sd-vae-ft-mse
        phrase: dreamlikeart
      - id: Fictiverse/Stable_Diffusion_PaperCut_Model
        vae: stabilityai/sd-vae-ft-mse
        phrase: papercut
      - id: Fictiverse/Stable_Diffusion_Microscopic_model
        vae: stabilityai/sd-vae-ft-mse
        phrase: microscopic
      - id: hassanblend/HassanBlend1.4
        vae: stabilityai/sd-vae-ft-mse
      - id: hassanblend/HassanBlend1.5.1.2
        vae: stabilityai/sd-vae-ft-mse
      - id: johnslegers/hasdx
        vae: stabilityai/sd-vae-ft-mse
      - id: nitrosocke/redshift-diffusion
        vae: stabilityai/sd-vae-ft-mse
        phrase: redshift style
      - id: plasmo/woolitize
        vae: stabilityai/sd-vae-ft-mse
        phrase: woolitize
      - id: prompthero/openjourney
        vae: stabilityai/sd-vae-ft-mse
        phrase: mdjrny-v4 style
      - id: SG161222/Realistic_Vision_V1.4
        vae: stabilityai/sd-vae-ft-mse
      - id: SG161222/Realistic_Vision_V2.0
        vae: stabilityai/sd-vae-ft-mse
      - id: SG161222/Realistic_Vision_V4.0_noVAE
        vae: stabilityai/sd-vae-ft-mse
      - id: SG161222/Realistic_Vision_V5.1_noVAE
        vae: stabilityai/sd-vae-ft-mse
      - id: SY573M404/f222-diffusers
        vae: stabilityai/sd-vae-ft-mse
      - id: wavymulder/Analog-Diffusion
        vae: stabilityai/sd-vae-ft-mse
        phrase: analog style
      - id: windwhinny/chilloutmix
        vae: stabilityai/sd-vae-ft-mse
      - id: XpucT/Deliberate
        vae: stabilityai/sd-vae-ft-mse
      - id: philz1337/reliberate
        vae: stabilityai/sd-vae-ft-mse

inpaint:
  - base: kandinsky_2_1
    pipelines:
      inpaint: KandinskyInpaintPipeline
    models:
      - id: kandinsky-community/kandinsky-2-1-inpaint
        id2: kandinsky-community/kandinsky-2-1-prior
  - base: sd_2_0
    pipelines:
      inpaint: StableDiffusionInpaintPipeline
      inpaint_controlnet: StableDiffusionInpaintControlNetPipeline
    models:
      - id: stabilityai/stable-diffusion-2-inpainting # official
  - base: sd_1_5
    pipelines:
      inpaint: StableDiffusionInpaintPipeline
      inpaint_controlnet: StableDiffusionInpaintControlNetPipeline
    models:
      - id: runwayml/stable-diffusion-inpainting # official
        vae: stabilityai/sd-vae-ft-mse
      - id: ghunkins/stable-diffusion-liberty-inpainting
        vae: stabilityai/sd-vae-ft-mse
      - id: parlance/dreamlike-diffusion-1.0-inpainting
        vae: stabilityai/sd-vae-ft-mse
      - id: lioo/Realistic_Vision_V2.0-inpainting
        vae: stabilityai/sd-vae-ft-mse
  - base: sdxl_1_0
    pipelines:
      inpaint: StableDiffusionXLInpaintPipeline
    models:
      - id: diffusers/stable-diffusion-xl-1.0-inpainting-0.1

upscale:
  - base: sd_2_0
    pipelines:
      upscale: StableDiffusionUpscalePipeline
    models:
      - id: stabilityai/stable-diffusion-x4-upscaler # official

controlnet:
  - base: sd_1_5
    pipelines:
      controlnet: StableDiffusionControlNetPipeline
    models:
      # Control Net Models
      - id: lllyasviel/control_v11p_sd15_canny
      - id: lllyasviel/control_v11f1p_sd15_depth
      - id: lllyasviel/control_v11p_sd15_inpaint
      - id: lllyasviel/control_v11p_sd15_lineart
      - id: lllyasviel/control_v11p_sd15_mlsd
      - id: lllyasviel/control_v11p_sd15_normalbae
      - id: lllyasviel/control_v11p_sd15_openpose
      - id: lllyasviel/control_v11p_sd15_scribble
      - id: lllyasviel/control_v11p_sd15_seg
      - id: lllyasviel/control_v11p_sd15_softedge
      - id: lllyasviel/control_v11e_sd15_shuffle
      - id: lllyasviel/control_v11f1e_sd15_tile
      - id: ioclab/control_v1p_sd15_brightness
      - id: monster-labs/control_v1p_sd15_qrcode_monster
      # T2I Adapter Models
      - id: TencentARC/t2iadapter_canny_sd15v2
        colourspace: L
     
  - base: sd_2_1
    pipelines:
      controlnet: StableDiffusionControlNetPipeline
    models:
      - id: thibaud/controlnet-sd21-canny-diffusers
      - id: thibaud/controlnet-sd21-depth-diffusers
      - id: thibaud/controlnet-sd21-hed-diffusers
      - id: thibaud/controlnet-sd21-openpose-diffusers
      - id: thibaud/controlnet-sd21-scribble-diffusers

  - base: sdxl_1_0
    pipelines:
      controlnet: StableDiffusionXLControlNetPipeline
    models:
    # Control Net Models
      - id: diffusers/controlnet-canny-sdxl-1.0-small
      - id: diffusers/controlnet-depth-sdxl-1.0-small
      - id: thibaud/controlnet-openpose-sdxl-1.0
    # T2I Adapter Models
      - id: TencentARC/t2i-adapter-canny-sdxl-1.0
        colourspace: L
