
generate:
  - base: flux
    pipelines:
      generate: FluxGeneratePipeline
    models:
      - id: black-forest-labs/FLUX.1-schnell
        revision: refs/pr/1
      - id: black-forest-labs/FLUX.1-dev
        revision: refs/pr/3
      - id: SG161222/RealFlux_1.0b_Dev/2 - Transformer Version/RealFlux_1.0b_Dev_Transformer.safetensors
  - base: kwai_kolors
    pipelines:
      generate: KwaiKolorsGeneratePipeline
    models:
      - id: Kwai-Kolors/Kolors-diffusers
  - base: auraflow
    pipelines:
      generate: AuraFlowGeneratePipeline
    models:
      - id: fal/AuraFlow
  - base: sd_3_0
    pipelines:
      generate: StableDiffusion3GeneratePipeline
    models:
      - id: stabilityai/stable-diffusion-3-medium-diffusers
      - id: stabilityai/stable-diffusion-3.5-large
      - id: stabilityai/stable-diffusion-3.5-large-turbo
  - base: pixart_sigma
    pipelines:
      generate: PixartSigmaGeneratePipeline
    models:
      - id: PixArt-alpha/PixArt-Sigma-XL-2-1024-MS
  - base: sc_1_0
    pipelines:
      generate: StableCascadeGeneratePipeline
    models:
      - id: stabilityai/stable-cascade
        prior: stabilityai/stable-cascade-prior
        decoder: stabilityai/stable-cascade
  - base: sdxl_1_0
    pipelines:
      generate: StableDiffusionXLGeneratePipeline
      animatediff: StableDiffusionXLAnimateDiffPipeline
    models:
      - id: stabilityai/stable-diffusion-xl-base-1.0
      - id: stabilityai/stable-diffusion-xl-refiner-1.0
      - id: playgroundai/playground-v2.5-1024px-aesthetic
      - id: RunDiffusion/Juggernaut-XL-v5
      - id: RunDiffusion/Juggernaut-X-v10
      - id: kitty7779/ponyDiffusionV6XL
        vae: stabilityai/sdxl-vae
        template: "score_9, score_8_up, score_8, {}"
        negtemplate: "score_6, score_5, score_4, {}"
      - id: GraydientPlatformAPI/ponyrealism21-xl
        vae: stabilityai/sdxl-vae
        template: "score_9, score_8_up, score_8, {}"
        negtemplate: "score_6, score_5, score_4, {}"
  - base: kandinsky_2_1
    pipelines:
      generate: KandinskyGeneratePipeline
      interpolate: KandinskyInterpolatePipeline
    models:
      - id: kandinsky-community/kandinsky-2-1
        id2: kandinsky-community/kandinsky-2-1-prior
  - base: df_1_0
    pipelines:
      generate: DeepFloydGeneratePipeline
    models:
      - id: DeepFloyd/IF-I-M-v1.0
        id2: DeepFloyd/IF-II-M-v1.0
        id3: stabilityai/stable-diffusion-x4-upscaler
      - id: DeepFloyd/IF-I-L-v1.0
        id2: DeepFloyd/IF-II-L-v1.0
        id3: stabilityai/stable-diffusion-x4-upscaler
      - id: DeepFloyd/IF-I-XL-v1.0
        id2: DeepFloyd/IF-II-L-v1.0
        id3: stabilityai/stable-diffusion-x4-upscaler
  - base: sd_2_1
    pipelines:
      generate: StableDiffusionGeneratePipeline
    models:
      - id: stabilityai/stable-diffusion-2-1  # official
      - id: stabilityai/stable-diffusion-2-1-base  # official
      - id: stablediffusionapi/illuminati-diffusion
  - base: sd_1_5
    pipelines:
      generate: StableDiffusionGeneratePipeline
      animatediff: StableDiffusionAnimateDiffPipeline
      pia: StableDiffusionPersonalizedImageAnimatorPipeline
    models:
      - id: runwayml/stable-diffusion-v1-5  # official
        vae: stabilityai/sd-vae-ft-mse
      - id: Aybeeceedee/knollingcase
        vae: stabilityai/sd-vae-ft-mse
        phrase: knollingcase
      - id: danbrown/Lyriel-v1-5
        vae: stabilityai/sd-vae-ft-mse
      - id: darkstorm2150/Protogen_v2.2_Official_Release
        vae: stabilityai/sd-vae-ft-mse
      - id: darkstorm2150/Protogen_x3.4_Official_Release
        vae: stabilityai/sd-vae-ft-mse
      - id: darkstorm2150/Protogen_x5.3_Official_Release
        vae: stabilityai/sd-vae-ft-mse
      - id: darkstorm2150/Protogen_x5.8_Official_Release
        vae: stabilityai/sd-vae-ft-mse
      - id: digiplay/Juggernaut_final
        vae: stabilityai/sd-vae-ft-mse
      - id: dreamlike-art/dreamlike-diffusion-1.0
        vae: stabilityai/sd-vae-ft-mse
        phrase: dreamlikeart
      - id: dreamlike-art/dreamlike-photoreal-2.0
        vae: stabilityai/sd-vae-ft-mse
        phrase: dreamlikeart
      - id: Fictiverse/Stable_Diffusion_PaperCut_Model
        vae: stabilityai/sd-vae-ft-mse
        phrase: papercut
      - id: Fictiverse/Stable_Diffusion_Microscopic_model
        vae: stabilityai/sd-vae-ft-mse
        phrase: microscopic
      - id: hassanblend/HassanBlend1.4
        vae: stabilityai/sd-vae-ft-mse
      - id: hassanblend/HassanBlend1.5.1.2
        vae: stabilityai/sd-vae-ft-mse
      - id: johnslegers/hasdx
        vae: stabilityai/sd-vae-ft-mse
      - id: nitrosocke/redshift-diffusion
        vae: stabilityai/sd-vae-ft-mse
        phrase: redshift style
      - id: plasmo/woolitize
        vae: stabilityai/sd-vae-ft-mse
        phrase: woolitize
      - id: prompthero/openjourney
        vae: stabilityai/sd-vae-ft-mse
        phrase: mdjrny-v4 style
      - id: SG161222/Realistic_Vision_V1.4
        vae: stabilityai/sd-vae-ft-mse
      - id: SG161222/Realistic_Vision_V2.0
        vae: stabilityai/sd-vae-ft-mse
      - id: SG161222/Realistic_Vision_V4.0_noVAE
        vae: stabilityai/sd-vae-ft-mse
      - id: SG161222/Realistic_Vision_V5.1_noVAE
        vae: stabilityai/sd-vae-ft-mse
      - id: SY573M404/f222-diffusers
        vae: stabilityai/sd-vae-ft-mse
      - id: wavymulder/Analog-Diffusion
        vae: stabilityai/sd-vae-ft-mse
        phrase: analog style
      - id: windwhinny/chilloutmix
        vae: stabilityai/sd-vae-ft-mse
      - id: XpucT/Deliberate
        vae: stabilityai/sd-vae-ft-mse
      - id: philz1337/reliberate
        vae: stabilityai/sd-vae-ft-mse

inpaint:
  - base: flux
    pipelines:
      generate: FluxGeneratePipeline
    models:
      - id: black-forest-labs/FLUX.1-Fill-dev
  - base: kandinsky_2_1
    pipelines:
      inpaint: KandinskyGeneratePipeline
    models:
      - id: kandinsky-community/kandinsky-2-1-inpaint
        id2: kandinsky-community/kandinsky-2-1-prior
  - base: sd_2_0
    pipelines:
      inpaint: StableDiffusionGeneratePipeline
    models:
      - id: stabilityai/stable-diffusion-2-inpainting # official
  - base: sd_1_5
    pipelines:
      inpaint: StableDiffusionGeneratePipeline
    models:
      - id: runwayml/stable-diffusion-inpainting # official
        vae: stabilityai/sd-vae-ft-mse
      - id: ghunkins/stable-diffusion-liberty-inpainting
        vae: stabilityai/sd-vae-ft-mse
      - id: parlance/dreamlike-diffusion-1.0-inpainting
        vae: stabilityai/sd-vae-ft-mse
      - id: yerang/Realistic_Vision_V4.0-inpainting
        vae: stabilityai/sd-vae-ft-mse
  - base: sdxl_1_0
    pipelines:
      inpaint: StableDiffusionXLGeneratePipeline
    models:
      - id: diffusers/stable-diffusion-xl-1.0-inpainting-0.1

upscale:
  - base: sd_2_0
    pipelines:
      upscale: StableDiffusionUpscalePipeline
    models:
      - id: stabilityai/stable-diffusion-x4-upscaler # official


controlnet:
  - base: sd_1_5
    models:
      - id: lllyasviel/control_v11p_sd15_canny
      - id: lllyasviel/control_v11f1p_sd15_depth
      - id: lllyasviel/control_v11p_sd15_inpaint
      - id: lllyasviel/control_v11p_sd15_lineart
      - id: lllyasviel/control_v11p_sd15_mlsd
      - id: lllyasviel/control_v11p_sd15_normalbae
      - id: lllyasviel/control_v11p_sd15_openpose
      - id: lllyasviel/control_v11p_sd15_scribble
      - id: lllyasviel/control_v11p_sd15_seg
      - id: lllyasviel/control_v11p_sd15_softedge
      - id: lllyasviel/control_v11e_sd15_shuffle
      - id: lllyasviel/control_v11f1e_sd15_tile
      - id: ioclab/control_v1p_sd15_brightness
      - id: monster-labs/control_v1p_sd15_qrcode_monster
        colourspace: L
  - base: sd_2_1
    models:
      - id: thibaud/controlnet-sd21-canny-diffusers
      - id: thibaud/controlnet-sd21-depth-diffusers
      - id: thibaud/controlnet-sd21-hed-diffusers
      - id: thibaud/controlnet-sd21-openpose-diffusers
      - id: thibaud/controlnet-sd21-scribble-diffusers
  - base: sdxl_1_0
    models:
      - id: diffusers/controlnet-depth-sdxl-1.0
        colourspace: L
      - id: xinsir/controlnet-canny-sdxl-1.0
      - id: xinsir/controlnet-openpose-sdxl-1.0
      - id: xinsir/controlnet-scribble-sdxl-1.0
      - id: monster-labs/control_v1p_sdxl_qrcode_monster
      - id: destitech/controlnet-inpaint-dreamer-sdxl
  - base: sd_3_0
    models:
      - id: InstantX/SD3-Controlnet-Canny
      - id: InstantX/SD3-Controlnet-Pose
      - id: InstantX/SD3-Controlnet-Tile
  - base: flux
    models:
      - id: InstantX/FLUX.1-dev-Controlnet-Canny
      - id: InstantX/FLUX.1-dev-Controlnet-Pose
      - id: InstantX/FLUX.1-dev-Controlnet-Tile
      - id: jasperai/Flux.1-dev-Controlnet-Upscaler
      - id: jasperai/Flux.1-dev-Controlnet-Depth
      - id: jasperai/Flux.1-dev-Controlnet-Surface-Normals

t2iadapter:
  - base: sd_1_5
    models:
      - id: TencentARC/t2iadapter_canny_sd15v2
        colourspace: L
  - base: sdxl_1_0
    models:
      - id: TencentARC/t2i-adapter-canny-sdxl-1.0
        colourspace: L


ipadapter:
  - base: sd_1_5
    models:
      - id: h94/IP-Adapter/models/ip-adapter_sd15.safetensors
      - id: h94/IP-Adapter/models/ip-adapter_sd15_light.safetensors
      - id: h94/IP-Adapter/models/ip-adapter-sd15_vit-G.safetensors
      - id: h94/IP-Adapter/models/ip-adapter-plus_sd15.safetensors
      - id: h94/IP-Adapter/models/ip-adapter-plus-face_sd15.safetensors
      - id: h94/IP-Adapter/models/ip-adapter-full-face_sd15.safetensors
  - base: sdxl_1_0
    models:
      - id: h94/IP-Adapter/sdxl_models/ip-adapter_sdxl.safetensors
      - id: h94/IP-Adapter/sdxl_models/ip-adapter_sdxl_vit-h.safetensors
      - id: h94/IP-Adapter/sdxl_models/ip-adapter-plus_sdxl_vit-h.safetensors
      - id: h94/IP-Adapter/sdxl_models/ip-adapter-plus-face_sdxl_vit-h.safetensors


ipadapterfaceid:
  - base: sd_1_5
    models:
      - id: h94/IP-Adapter-FaceID/ip-adapter-faceid_sd15.bin
      - id: h94/IP-Adapter-FaceID/ip-adapter-faceid-portrait_sd15.bin
      - id: h94/IP-Adapter-FaceID/ip-adapter-faceid-plus_sd15.bin
      - id: h94/IP-Adapter-FaceID/ip-adapter-faceid-plusv2_sd15.bin
  - base: sdxl_1_0
    models:
      - id: h94/IP-Adapter-FaceID/ip-adapter-faceid_sdxl.bin
      - id: h94/IP-Adapter-FaceID/ip-adapter-faceid-plusv2_sdxl.bin


video:
  - base: cogvideox_i2v
    pipelines:
      generate: CogVideoXGeneratePipeline
    models:
      - id: THUDM/CogVideoX-5b-I2V
  - base: cogvideox_v2v
    pipelines:
      generate: CogVideoXGeneratePipeline
    models:
      - id: THUDM/CogVideoX-5b-trail
  - base: cogvideox_t2v
    pipelines:
      generate: CogVideoXGeneratePipeline
    models:
      - id: THUDM/CogVideoX-5b
      - id: THUDM/CogVideoX-2b
  - base: svd_1_0
    pipelines:
      generate: StableVideoDiffusionGeneratePipeline
    models:
      - id: stabilityai/stable-video-diffusion-img2vid
      - id: stabilityai/stable-video-diffusion-img2vid-xt
      - id: stabilityai/stable-video-diffusion-img2vid-xt-1-1
  - base: sd_1_5
    models:
      - id: vladmandic/animatediff-v3
    loras:
      - id: guoyww/animatediff-motion-lora-zoom-in
      - id: guoyww/animatediff-motion-lora-zoom-out
      - id: guoyww/animatediff-motion-lora-pan-left
      - id: guoyww/animatediff-motion-lora-pan-right
      - id: guoyww/animatediff-motion-lora-tilt-up
      - id: guoyww/animatediff-motion-lora-tilt-down
      - id: guoyww/animatediff-motion-lora-rolling-clockwise
      - id: guoyww/animatediff-motion-lora-rolling-anticlockwise
  - base: sdxl_1_0
    models:
      - id: guoyww/animatediff-motion-adapter-sdxl-beta


tts:
  piper_1_0:
    models:
      - name: en_GB Southern English Female Low
        id: rhasspy/piper-voices/en/en_GB/southern_english_female/low/en_GB-southern_english_female-low.onnx
      - name: en_GB Alba Medium (Scottish)
        id: rhasspy/piper-voices/en/en_GB/alba/medium/en_GB-alba-medium.onnx
      - name: en_GB Aru Medium (12 voices)
        id: rhasspy/piper-voices/en/en_GB/aru/medium/en_GB-aru-medium.onnx
      - name: en_GB Cori Medium
        id: rhasspy/piper-voices/en/en_GB/cori/medium/en_GB-cori-medium.onnx
      - name: en_GB Cori High
        id: rhasspy/piper-voices/en/en_GB/cori/high/en_GB-cori-high.onnx
      - name: en_GB Jenny Dioco Medium (Irish)
        id: rhasspy/piper-voices/en/en_GB/jenny_dioco/medium/en_GB-jenny_dioco-medium.onnx
      - name: en_GB Semaine Medium (4 voices)
        id: rhasspy/piper-voices/en/en_GB/semaine/medium/en_GB-semaine-medium.onnx
      - name: en_GB VCTK Medium (109 voices)
        id: rhasspy/piper-voices/en/en_GB/vctk/medium/en_GB-vctk-medium.onnx
      - name: en_US Amy Medium
        id: rhasspy/piper-voices/en/en_US/amy/medium/en_US-amy-medium.onnx
      - name: en_US Arctic Medium (18 voices)
        id: rhasspy/piper-voices/en/en_US/arctic/medium/en_US-arctic-medium.onnx
      - name: en_US Arctic L2 Medium (24 voices)
        id: rhasspy/piper-voices/en/en_US/l2arctic/medium/en_US-l2arctic-medium.onnx
      - name: en_US HFC Female Medium
        id: rhasspy/piper-voices/en/en_US/hfc_female/medium/en_US-hfc_female-medium.onnx
      - name: en_US Kristin Medium
        id: rhasspy/piper-voices/en/en_US/kristin/medium/en_US-kristin-medium.onnx
      - name: en_US Kusal Medium
        id: rhasspy/piper-voices/en/en_US/kusal/medium/en_US-kusal-medium.onnx
      - name: en_US Lessac High
        id: rhasspy/piper-voices/en/en_US/lessac/high/en_US-lessac-high.onnx
      - name: en_US Libritts High
        id: rhasspy/piper-voices/en/en_US/libritts/high/en_US-libritts-high.onnx