number:
  - "a"
  - "one"
  - "two"
  - "three"
view:
  - "from side"
  - "from behind"
  - "from front"
  - "from above"
  - "from below"
nationality:
  - ""
  - "asian"
  - "indian"
  - "cambodian"
  - "chinese"
  - "korean"
  - "thai"
  - "vietnamese"
  - "japanese"
  - "malaysian"
  - "filipino"
  - "african"
  - "nigerian"
  - "egyptian"
  - "moroccan"
  - "gambian"
  - "kenyan"
  - "ghanaian"
  - "chilean"
  - "brazilian"
  - "venezuelan"
  - "mexican"
  - "greek"
  - "spanish"
  - "ukrainian"
period:
  - ""
  - "ancient"
  - "medieval"
  - "renaissance"
  - "modern"
  - "futuristic"
  - "contemporary"
  - "victorian"
  - "edwardian"
  - "georgian"
  - "elizabethan"
  - "jacobean"
  - "1880s"
  - "1890s"
  - "1900s"
  - "1910s"
  - "1920s"
  - "1930s"
  - "1940s"
  - "1950s"
  - "1960s"
  - "1970s"
  - "1980s"
colour:
  - "black"
  - "white"
  - "red"
  - "green"
  - "blue"
  - "turquoise"
  - "jade"
  - "pink"
hairstyle:
  - "pixie cut"
  - "buzz cut"
  - "bixie"
  - "short shag"
  - "undercut"
  - "cropped curls"
  - "tapered cut"
  - "classic bob"
  - "lob"
  - "blunt cut"
  - "layered mid-length"
  - "shag"
  - "wolf cut"
  - "shoulder-length waves"
  - "midi curly cut"
  - "straight and sleek"
  - "long layers"
  - "feathered cut"
  - "boho waves"
  - "mermaid hair"
  - "v-cut"
  - "u-cut"
  - "curtain layers"
  - "afro"
  - "twist-out"
  - "bantu knots"
  - "wash and go"
  - "finger coils"
  - "curly bob"
  - "pineapple updo"
  - "messy bun"
  - "low chignon"
  - "french twist"
  - "top knot"
  - "braided bun"
  - "space buns"
  - "elegant updo"
  - "french braid"
  - "dutch braid"
  - "fishtail braid"
  - "box braids"
  - "cornrows"
  - "halo braid"
  - "milkmaid braids"
  - "curtain bangs"
  - "blunt bangs"
  - "side-swept bangs"
  - "wispy bangs"
  - "micro bangs"
  - "mullet"
  - "shaved patterns"
  - "dip dye"
  - "peekaboo color"
  - "rainbow hair"
  - "crimped hair"
  - "wet look"
