number:
  - "a"
  - "one"
  - "two"
  - "three"
view:
  - "from side"
  - "from behind"
  - "from front"
  - "from above"
  - "from below"
nationality:
  - ""
  - "asian"
  - "indian"
  - "cambodian"
  - "chinese"
  - "korean"
  - "thai"
  - "vietnamese"
  - "japanese"
  - "malaysian"
  - "filipino"
  - "african"
  - "nigerian"
  - "egyptian"
  - "moroccan"
  - "gambian"
  - "kenyan"
  - "ghanaian"
  - "chilean"
  - "brazilian"
  - "venezuelan"
  - "mexican"
  - "greek"
  - "spanish"
  - "ukrainian"
period:
  - ""
  - "ancient"
  - "medieval"
  - "renaissance"
  - "modern"
  - "futuristic"
  - "contemporary"
  - "victorian"
  - "edwardian"
  - "georgian"
  - "elizabethan"
  - "jacobean"
  - "1880s"
  - "1890s"
  - "1900s"
  - "1910s"
  - "1920s"
  - "1930s"
  - "1940s"
  - "1950s"
  - "1960s"
  - "1970s"
  - "1980s"
colour:
  - "black"
  - "white"
  - "red"
  - "green"
  - "blue"
  - "turquoise"
  - "jade"
  - "pink"
